### PR TITLE
homework updates

### PR DESCRIPTION
**Pull request by WhatTheHill**

### CODE REVIEW

**Comment by ZoeLawson** [comment]
There's a very annoying merge conflict that I can't fix. (I tried.) 
Can you please run the following command? You need to figure out where git is on your system (the git.exe is hidden in your user directory on Windows). You need to have your command window be in your mcc_tools_tech folder.

git checkout --ours mcchandout/HillaryIanatosca.pdf

Then commit and push the change.
I'm really, really hoping that will fix this issue.

**Comment by WhatTheHill** [comment]
Oh boy. I’ve been on the hunt for a while and this is definitely not coming up for me. I’m also nkt clear on your instructions “fit needs to be in the Mcc folder/git checkout ”On Apr 16, 2024, at 9:38 PM, Zoë Lawson ***@***.***> wrote:﻿
There's a very annoying merge conflict that I can't fix. (I tried.)
Can you please run the following command? You need to figure out where git is on your system (the git.exe is hidden in your user directory on Windows). You need to have your command window be in your mcc_tools_tech folder.
git checkout --ours mcchandout/HillaryIanatosca.pdf
Then commit and push the change.
I'm really, really hoping that will fix this issue.

**Comment by ZoeLawson** [comment]
If you look at the Pull Request (https://github.com/ZoeLawson/mcc_tools_tech/pull/386) there should be a section that says "This branch has conflicts that must be resolved" and there's a link to "Use the command line". Those are the instructions I need you to follow.
IIRC, you are using a Mac. You need to do things via the terminal window and using git commands. Since I'm not familiar with Macs, I'm fuzzy on the details.

**Comment by WhatTheHill** [comment]
I am definitely not using a mac. but i found the space in github online where it tells me the branch has conflicts and needs to be resolved. there is no link to use command line unless it is called something else? what does that prompt look like? the options i am given when i click on the sync fork button are ‘discard 2 commits’ and open pull request'

**Pull request closed without merging**
