### PR TITLE
UI mockup_revised

### PR DESCRIPTION
**Pull request by Yaks888**

### CODE REVIEW

**Comment by ZoeLawson** [comment]
Really close!
1. Can you remove the version of the file that's in the root of the repo? 
2. The PDF (PID.pdf in mcc_tools_tech\Week02-ProgressiveInfo) has specific instructions about the file name of your properties file. The automation doesn't work unless you name your file the correct thing and put it in the right location.

Thanks!

**Comment by ZoeLawson** [comment]
Almost there!
As we discussed in class, this pull request currently contains the file in the root directory, not in the week 2 homework folder.
Also, rename the file per the PDF you just discovered.
Since this PR is already open, when you push your commits to your fork, the changes should just show up here.

**Comment by ZoeLawson** [comment]
I've merged the pull request, but there are still a few issues.
1. There's still a file in the root directory that needs to be removed. (login_MYakavonis.Properties)
2. You made a file in the correct directory (Week02-ProgressiveInfo\Homework\login_MYakavonis.properties.Properties), but it needs to be named MichaelYakavonis.properties. Once you do that, the automation should create an HTML file for you.
But you got files up to git! Congrats! Now you can do more practice. :-)

**Comment by Yaks888** [comment]
Ahh, thank you for (re)explaining! Think I finally got it through my thick
skull :)

Maybe!

**Comment by ZoeLawson** [comment]
This takes repetition. I spent hours arguing with git before it started making sense. 
You almost have the name right. Right now there are two .properties (MichaelYakavonis.properties.Properties instead of MichaelYakavonis.properties)
By default, Windows "hides known file extensions", which I think is terrible. In mcc_tools_tech/Handouts/tips_and_tricks.pdf there's a section "File Explorer configuration" that tells you how to fix the setting.

**Pull request merged**
