### PR TITLE
RestructuredText_Output

### PR DESCRIPTION
**Pull request by Yaks888**

### CODE REVIEW

**Comment by ZoeLawson** [comment]
Out of curiosity, what is the purpose of the Source Output.url ?

**Comment by Yaks888** [comment]
...an excellent question! No purpose whatsoever, sadly -- I was
overthinking things there. As you mentioned during last night's class,
you'll be using ReadTheDocs as the vehicle for the .RST assignment output.

My audio difficulties last night prevented me from uttering a single word
(eye roll). I'll be sure to remedy that moving forward!!

Have a terrific weekend!

**Comment by Yaks888** [comment]
Hi!

The Zoom recording for this week's class doesn't appear to be available on
Blackboard. Every previous week's recording is showing, just not this past
week's.

Do you have any different access to the Zoom recordings than we would?
Maybe it's available to you for download somewhere?

Thanks for checking!
Mike

**Comment by ZoeLawson** [comment]
Sorry, forgot to respond directly. 
I have to flip a switch to make the recording available to you. It can take an hour after class for the switch to activate. I sometimes go to bed before midnight ;-) And then I forgot to log in to my MCC computer to flip it on Friday. 
Apologies for being late!

**Pull request merged**
