### PR TITLE
Changed name of .properties file

### PR DESCRIPTION
**Pull request by spbrown001**
Changed name of .properties file per Zoe

### CODE REVIEW

**Comment by ZoeLawson** [comment]
Thanks! This generated StephenBrown.html, so if you sync with the class repo, you can see what the changes in the properties file did.

**Comment by spbrown001** [comment]
Zoe,
Hi, I wasn't sure if I could respond directly to this or not, but there is a handy-dandy note on the bottom that says I can.
I can see the StephenBrown.html file here:https://github.com/spbrown001/mcc_tools_tech/tree/Winter2022/Week02-ProgressiveInfo/Homework

StephenBrown.htmlDeploying to Winter2022 from @***@***.*** 🚀15 hours ago
But when I go to my local directory:C:\Users\s_p_brown\Desktop\Personal\GitHub\mcc_tools_tech\Week02-ProgressiveInfo\Homework

I don't see the new html file. 
I did a Fetch Origin from the GitHup GUI and it says "Fetch Origin" Last fetched 21 mins ago (9:39am).I tried a pull request open and it says there is nothing to compare. 
When I'm here:https://github.com/spbrown001/mcc_tools_tech
or here:https://github.com/spbrown001/mcc_tools_tech/tree/Winter2022/Week02-ProgressiveInfo/Homework

It says, "This branch is up to date with ZoeLawson:Winter2022"
Am I missing something? I thought my local directory would add the new html file. I can't find a "sync" option and I think its sync'd already?  
Hope this makes sense, GitHub is definitely confusing. -Steve

    On Tuesday, February 8, 2022, 06:59:49 PM EST, Zoë Lawson ***@***.***> wrote:  
 
 


Thanks! This generated StephenBrown.html, so if you sync with the class repo, you can see what the changes in the properties file did.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZoeLawson** [comment]
Sync is a generic term for getting your files the same everywhere. 
I'm pretty sure you've done this, but to confirm:
1. You did a Fetch Upstream from your fork of the class repo in GitHub. 
I'm pretty sure you did this because the HTML file is in your fork, and it says "This branch is up to date with ZoeLawson:Winter2022."
2. You did a Fetch Origin from the GitHub Desktop GUI. 
Fetch gets the information from the remote repository that there are changes, but it doesn't actually MAKE the changes locally.  
Is there now a Blue "Pull from Origin" button somewhere?
If not, see if you can force it, using **Repository > Pull**.
3. Did you refresh Windows File Explorer? Sometimes Windows is dumb and doesn't show you the changes.
4. Have you confirmed that GitHub desktop is pointing to the correct repository and the correct branch?
5. You tried using the command line. Has that confused your connection? (I actually have two copies of my repos, one I use with the command line, and a separate one I use with GitHub Desktop.)

Yes, Git and GitHub is definitely confusing.

Those are my first attempts at troubleshooting. Crossing my fingers one of these helps.

Zoë

**Comment by ZoeLawson** [comment]
With class today, were you able to figure out how to get the files to your system?

**Pull request merged**
