### PR TITLE
striving to do assignments  

### PR DESCRIPTION
**Pull request by TheDFF**
I learned something, but much needs to be done about copying files and renaming them.

### CODE REVIEW

**Comment by ZoeLawson** [comment]
So, unfortunately, you miss understood some of the instructions. You did not need to copy the homework folder, but a specific file in the homework folder.
I've tried to write explicit steps for you. See the attached PDF. 
[How_to_fix_your_homework_DL_8Mar2023.pdf](https://github.com/ZoeLawson/mcc_tools_tech/files/10926879/How_to_fix_your_homework_DL_8Mar2023.pdf)
(And let me know if you have trouble getting the PDF.)

**Comment by TheDFF** [comment]
Zoë;
Your Instructions could not be any easier, yet, I thing I messed it up.  I do not have the file in my homework folder.   “login.properties” in explorer: Document>GitHub>mcc_ools_tech>Wee02-ProgressiveInfo> Homework;   I was elsewhere in Git and I think I deleted it.  Only I do this mess.  Good thing, I am learning more about GitHub.    
I see it in GitHub, but when I copy it does not paste. 
I am

**Comment by ZoeLawson** [comment]
1. Did you follow the steps I recommended back in week 1 or 2 about following the steps in "File Explorer configuration" in the Handouts/tips_and_tricks.pdf? 
I wonder if you don't have file extensions visible, which might be confusing things.
2. If that doesn't help: 
    a. Go to https://github.com/TheDFF/mcc_tools_tech/blob/Winter2023/Week02-ProgressiveInfo/Homework/login.properties.
    b. Copy the text in the file (from `LoginPage=Login`...through `GraphicAlt=Alt text goes here` 
    c. Save the text in a text file, naming the file DecioLeonardo.properties.

**Comment by TheDFF** [comment]
I got it.  
It was there all along.  I was looking for “login**.properties**”.  Only after carefully following your second set of instructions did I realize that the file is simple “**login**”.  I verified that by the snip shot I took at the beginning to show you.
Then I verified by comparing my file to my pears’ files, and it looked alike.   I had the file open a few times but I did not recognize it.
Thank you, Zoë.
Décio

**Comment by ZoeLawson** [comment]
Yay! Glad you figured it out!
So, the problem is you don't have your Windows Explorer configured properly. That is something I strongly recommend. With the files we're going to be working with, hiding known file extensions gets to be very confusing.

You still need to delete the `homework-copy` folder or move it somewhere outside of the mcc_tools_tech folder. I don't want extra copies of files hanging around in the class repository.

After that fix, open a new pull request so I can get the changes.

Hope this helps,
Zoë

**Comment by TheDFF** [comment]
Yes, it is all clear, now.
Thanks for your help.
Decio

**Comment by ZoeLawson** [comment]
Congrats! 
When you sync with the class repo, you'll find a DecioLeonardo.html file in the week 2 homework folder. That file was generated based on your changes to the DecioLeonardo.properties file.
Well done!

**Pull request merged**
