### PR TITLE
Create TW_ReformattingWeek3Todd.docx

### PR DESCRIPTION
**Pull request by TAB-Bear**
Hi Zoe,
Week 3 homework is here: C:\Users\tburns\Documents\GitHub\mcc_tools_tech\Week03-WordOffice\Homework. Also attached
[TW_ReformattingWeek3Todd.docx](https://github.com/ZoeLawson/mcc_tools_tech/files/4200800/TW_ReformattingWeek3Todd.docx)

Best, Todd

### CODE REVIEW

**Comment by TAB-Bear** [comment]
Hi Zoe,
I am not certain I executed this Git process correctly, although I feel comfortable that I reformatted properly. Best, Todd

**Comment by ZoeLawson** [comment]
All you did was close the pull request before I could merge it in. 
If you re-open the request, I can merge it in to my Winter2020.

**Comment by TAB-Bear** [comment]
Just reopened it. Note to self: wait to close!

**Comment by TAB-Bear** [comment]
Success! Thank you!

**Comment by ZoeLawson** [comment]
Yup, it's the job of the "Powers that Be" to review and either merge and close or just close/reject a Pull Request.

An open PR is the 'flag' to me that there's something I need to merge in. 

You can close a pull request if you realize that you left out a chapter or forgot to save or whatever.

**Comment by TAB-Bear** [comment]
Gotcha - makes sense

**Pull request merged**
