### PR TITLE
reStructured text homework

### PR DESCRIPTION
**Pull request by tlkay**
week 7 homework

Also, here is the link to my read the docs file.... I think this is the right link?
https://therese-kay-tkrtd-tutorial.readthedocs-hosted.com/en/latest/

### CODE REVIEW

**Comment by ZoeLawson** [comment]
Before I merge this, did you intend to include the extra markup specification documents? Looks like there's an HTML file with a folder containing CSS that I don't think is part of your homework.

**Comment by tlkay** [comment]
Thanks, Zoë,
I'm not sure how I created that - maybe when I was trying to figure things
out. I think the only thing should be the folder TKreStructuredText_HW.
So, I should delete the other things and that should update....

Before I do that and delete something I shouldn't - How do I find that pull
request? Never mind.... poke around long enough and you find it! LOL

So, I deleted those extra mystery files and created a new pull request. Is
that what I should have done?

*Therese Kay*

Linked In: https://www.linkedin.com/in/theresekay/

Website: www.Theresekay.com <http://www.theresekay.com/>

Amazon Author Page:
https://www.amazon.com/stores/Therese-Kay/author/B077CKLD5S

**Comment by ZoeLawson** [comment]
Yay, the RST files are sorted! Thank you.

I am happy that you went forward and did a bunch of exciting, complicated things in Flare.

However, everyone is using the same project. You have swapped out the TOC to use your new TOC, which wipes out everyone else's content. Welcome to the joy of working in shared projects. :-)

You can update the main TOC to reference your new TOC, but you can't replace it entirely. Does that make sense? 
(I'm guessing by looking at the raw text changes)

**Comment by tlkay** [comment]
Oh no!
I understand what you are saying but I don't know what I did or how to
accomplish that unpleasant feat.  I did accidentally delete the original
page that you created for me and then I just created a new one - did that
do it maybe?

It had me wondering... is there a way I could have worked on my part of the
file in a different project and then import those pieces into the group
project?

One thing I noticed when I imported this word file and was fiddling with it
- the tables that were in Word did not translate into Flare. I'm hoping to
figure that out before Thursday but.... hmmm not sure I'll get there. I've
been a little under the weather.

*Therese Kay*

Linked In: https://www.linkedin.com/in/theresekay/

Website: www.Theresekay.com <http://www.theresekay.com/>

Amazon Author Page:
https://www.amazon.com/stores/Therese-Kay/author/B077CKLD5S

**Comment by ZoeLawson** [comment]
Any chance you can update the targets to use the original Online and PDF TOCs? And then include your Journey to Health TOC in the main Online and PDF tocs?

**Comment by tlkay** [comment]
Hi Zoe!
Sorry for the late reply. I had a hard time figuring it out.
I *think* I finally reset the Online TOC but not entirely sure. Not sure
where the PDF one lives.
Definitely have no idea how to move the Journey to Health TOC anywhere
other than where it is - which is now... nowhere?

I think I bit off more than I can chew with this.


[image: image.png]

*Therese Kay*

Linked In: https://www.linkedin.com/in/theresekay/

Website: www.Theresekay.com <http://www.theresekay.com/>

Amazon Author Page:
https://www.amazon.com/stores/Therese-Kay/author/B077CKLD5S

**Pull request merged**
