### PR TITLE
Week 8 and 9 Homework- FrameMaker-JM

### PR DESCRIPTION
**Pull request by juliomadridmcc**

### CODE REVIEW

**Comment by ZoeLawson** [comment]
This PR contains a copy of the 7.5x9 template. There are also changes to two of the template files that I'd rather not include. Can you look into reverting the template files?
Thanks!

**Comment by ZoeLawson** [comment]
Your last commit contains changes to files in the FrameMaker Template folder. 
I'm trying to keep those template files untouched so that weird things don't happen. 
Most likely the change is that you opened the file and clicked okay on missing fonts or something, but it's also possible that you accidentally wrote over them. (I've done it too.)
Can you please undo your last commit (https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit). Then in GitHub desktop, don't select all the files, but only select the files in the homework folder to commit.
Let me know if you need more details.

Thanks!

**Comment by juliomadridmcc** [comment]
Hi Zoe,

I tried to undo my last commit (Week 8-9 HW- FrameMaker-JM-2.0) and got the
attached error message. How should I proceed?

Best regards,

Julio Madrid

**Comment by ZoeLawson** [comment]
Unfortunately the error message didn't come through.
I want to make sure I can get your local Git situation sorted. Can you try to cut and paste the error as text? 

I have another theory about how to fix it. It's a bit of a pain, but git is a pain about undoing boo-boos. But I want to be sure your local repo is in a stable state first.

(And don't feel bad. I wiped out the branch accidentally and had to restore it. You're not the only one that argues with Git.)

**Comment by juliomadridmcc** [comment]
This is the message:

error: Your local changes to the following files would be overwritten by
merge: Week08-Framemaker/Homework/ExampleHomework/JMChapter1.fm
Week08-Framemaker/Homework/ExampleHomework/Week8HW_Framemaker_JM.book
Please commit your changes or stash them before you merge. Aborting fatal:
revert failed

**Comment by ZoeLawson** [comment]
Okay, your system should be in a stable state.
I'm going to merge this PR and clean up the files on my side. 
One of my major concerns with Git is that cleaning up mistakes is more difficult than it should be. 
If I were sitting with you, I'd suggest that you go into GitHub, download the unchanged versions of the template files from my repo, replace the versions on your system, and then recommit them. Which would undo the change. Or possibly argue with some funky command line tools. 
But I can do the copying locally and save you the trouble. I've done it for coworkers multiple times over the years. (And I've asked developers with more git experience than me to fix things I've thoroughly borked.)

**Comment by juliomadridmcc** [comment]
I really appreciate the help, Zoe. Thank you.

- Julio Madrid

**Pull request merged**
