### PR TITLE
disco

### PR DESCRIPTION
**Pull request by amacgown00**

### CODE REVIEW

**Comment by ZoeLawson** [comment]
Somehow there are conflicts in the Homework/myFirstSphinxProject.
Can you please resolve those?

**Comment by lisa-source** [comment]
Hi Zoë,

Certainly, I will work on resolving the Sphinx docs issue.

I was trying to set up my portfolio in my personal git repo (not MCC) and
faced some issues with Sphinx. It seems this may have had an impact on
Homework/myFirstSphinxProject.

-Lisa

**Comment by ZoeLawson** [comment]
@lisa-source - How did you get notified about a message to @amacgown00 ? 
I don't care who fixes it, just trying to sort out how the heck GitHub notifications work. :-)

**Comment by lisa-source** [comment]
Sorry, my mind is mush. That message was not for me. 😀

I’m on the “watch” list for notifications in GitHub. I just clicked Watch
in GitHub so I see notifications.

**Comment by amacgown00** [comment]
I think I fixed it

It's not good when I make merge mistakes but it always feels satisfying to know how to fix them!!!!!!!!!!!!!!

**Comment by ZoeLawson** [comment]
Did you close the PR on purpose so you can fix things and make a new PR? 
If you close the PR, I can't merge it :-)

And yes fixing things always feels good. It's why you keep banging your head against problems. It's so fabulous when you break through.

**Pull request closed without merging**
