### PR TITLE
Week 4 Homework Melinda

### PR DESCRIPTION
**Pull request by MTYTH**
Week 4 Homework Melinda

### CODE REVIEW

**Comment by ZoeLawson** [comment]
Yay! I can see it!

Looks like one of your files somehow had a merge conflict in it. I'm guessing that's one of the errors you saw. 

I'm going to merge this pull request anyway. Fixing the merge issue is something we should do together (if there's anything that really needs to be fixed.)

**Comment by MTYTH** [comment]
Sounds good. Thanks. But, you only have Week 4, right? I know I'm bumbling around. I understand the concept, but it just isn't becoming any more natural.

**Comment by ZoeLawson** [comment]
Having it feel natural only comes with familiarity. It took me months of constant use, and I can still be surprised, never mind be confused by a feature I don't use much.
Git is a PITA and not easy to learn, so you’re actually doing quite well, all things considered.

There's a files tab on GitHub.com that shows you what files are included.

This includes week 3 and 5, nothing for Week 4.

Zoë Lawson
(she/her)
________________________________

**Comment by MTYTH** [comment]
Okay. I'll take a look for Week 4 and create a pull request.

**Pull request merged**
