### PR TITLE
Winter2020

### PR DESCRIPTION
**Pull request by abweiner18**
I deleted the original login.properties file by mistake when I made my new text file. Then I tried to copy it back into my repo. Suffice it say, take a look at all my commits and deny whatever needs to be denied. Feel free to deny the whole thing too. :)

### CODE REVIEW

**Comment by ZoeLawson** [comment]
I am not going to complete this pull request because you accidentally deleted the file. That change will delete the file for everyone else, which would not be ideal. :-) 
You need to restore the file, and add and commit it.
Go into my repo in Git Hub and copy the login.properties file to your local dir and re-add.

Trying to recover the file via Git commands is way too complicated. (This is how I do it at work)

FYI, since you have a PR (Pull Request) open, when you add, commit, and push changes, the PR will automatically pick them up. Once a PR is open, you don't need to make a new one. It's open until it is merged or closed.

**Comment by abweiner18** [comment]
In the current pull request, I restored the deleted file (at least I think
so). If you look at the 3 commits in the pull request, one of them is the
restoration of the document. I went into your repo and copied that file and
added it back to my repo. Relook at the pull request and let me know. My
remote Winter2020 branch has the file restored, if you can see that.

So weird, I assumed you could just deny the pull request. It seems weird
that you -- the gatekeeper -- can't deny a pull request. Isn't that what
the gatekeeper is for, to prevent dweebs like me from making dumb mistakes?
Oh well.

Let me know next steps. btw, I'm soooo happy I get to make mistakes like
this now, in class, instead of at work. Also, just talking to someone do
does weird tech/analyst stuff who said how valuable it is to know git.
Thanks!!

**Comment by ZoeLawson** [comment]
I can close Pull Requests without merging them. 
However, in the Git system I am used to, you can also mark a pull request as "Needs Work", so I'm used to keeping pull requests open when in the back-and-forth phase of sorting out what needs to be fixed.

You did add back a login.properties. However, somehow the version of the file you uploaded has no content. You can see by looking at https://github.com/abweiner18/mcc_tools_tech/blob/Winter2020/Week02-ProgressiveInfo/Homework/login.properties

**Comment by ZoeLawson** [comment]
Congrats!
Your commit messages read like many of the messages I read at work. :-)

**Comment by ZoeLawson** [comment]
If you sync with my repo, you should get your generated HTML files.

FYI, I changed the file names to not include spaces so that my tools would work. (Spaces in file names and scripting does terrible, terrible things.)

**Pull request merged**
