### PR TITLE
resending_homework

### PR DESCRIPTION
**Pull request by sshahana2024**

### CODE REVIEW

**Comment by ZoeLawson** [comment]
Hey there - there are two files in the root of the class repo (New Compressed (zipped) Folder.zip and New Microsoft Publisher Document.pub) that shouldn't be there.
Can you please remove these files from the folder and commit the change? Then I'll merge the pull request.
Thank you!

**Comment by sshahana2024** [comment]
Hello Zoe,I deleted two files, and committed to the changes, but am not sure if I did it correctly? Thanks!Shahana
    On Thursday, February 22, 2024 at 11:17:11 PM EST, Zoë Lawson ***@***.***> wrote:  
 
 


Hey there - there are two files in the root of the class repo (New Compressed (zipped) Folder.zip and New Microsoft Publisher Document.pub) that shouldn't be there.
Can you please remove these files from the folder and commit the change? Then I'll merge the pull request.
Thank you!

**Comment by ZoeLawson** [comment]
You didn't do anything _wrong_,  you just had files in the folder and committed them to Git. Easy enough to do. I'm just trying to keep the class repo tidy. :-)
Unfortunately in the process, you also accidentally deleted some of your submissions. Things that are confused:
* deleted Week02-ProgressiveInfo/Homework/login.properties
   Recommend you download it from the class repo and put it in your local folder to restore it.
* Accidentally deleted your Week 3 homework. 
   If you click on the "This branch is 14 commits ahead" link, you should get to a list of all the commits that haven't been merged yet. Scroll down to [shahana_sharmin_hw_wk3](https://github.com/ZoeLawson/mcc_tools_tech/commit/9498df59ec098bfc3e658ff3451589dd9c7541f6) (or click that link). Click the three dots on the right-hand side in the same bar as the file name and select *View file*. Then click *Download raw file*. You can get your original file back. 
* New Compressed (zipped) Folder.zip is still in the root directory. Delete that file, please.

I recommend that you don't try undo any commits. Reverting commits is complicated unless you understand what's going on. And, you can only revert the ENTIRE commit. If your commit contains 3 files, and you only want to revert one file, you can't do it easily. You end up reverting all 3 files, which is rarely what you want to do. It's usually easier to find the version of the file you want to save from github.com, download it, and overwrite it locally. 

This is a lot of detail in a small space, I can walk you through it when you have time. Or if you need me to type it up with images, let me know.

**Comment by ZoeLawson** [comment]
Yay we fixed it!

**Comment by sshahana2024** [comment]
Thanks!
    On Sunday, March 17, 2024 at 01:06:02 PM EDT, Zoë Lawson ***@***.***> wrote:  
 
 


Yay we fixed it!

**Pull request merged**
