### PR TITLE
Merge Issue Attempt

### PR DESCRIPTION
**Pull request by amacgown00**
trying to create a merge problem for final project

### CODE REVIEW

**Comment by ZoeLawson** [comment]
This PR doesn't have a merge issue.
Do you want me to make a change to create a merge issue?

**Comment by amacgown00** [comment]
I made a merge issue by accident so I think I'm good

**Comment by ZoeLawson** [comment]
Yay happy accidents.
Need me to merge this PR, or do you need me to keep it open?

**Comment by amacgown00** [comment]
You can merge it

**Pull request merged**
