### PR TITLE
Winter2020

### PR DESCRIPTION
**Pull request by jasmineplex**
Homework for Week4

### CODE REVIEW

**Comment by ZoeLawson** [comment]
Can you please double-check your repository?
This PR has 38 files in it, and most of them are renaming/moving CSS files into the Week2 homework folder. There are also some changes to other people's homework files. You may also be behind on a pull from my Winter2020.
You don't need to make another PR, you just need to fix things locally and then push the changes to your repo. Then this open PR will automagically pick up the changes.
Please reach out if this doesn't make any sense.

**Comment by jasmineplex** [comment]
Ahhh sorry!!!! I pushed and pulled in a rush yesterday and I now remember I
forgot to push locally. I’ll fix this. Thanks for letting me know.

Andrea

**Comment by jasmineplex** [comment]
I'm trying to figure out how to address this, do I manually delete files in Github or am I missing some magic command line function that will clean up my repo? I am trying to abstain from immediately resorting to a pull request

**Comment by ZoeLawson** [comment]
What I recommend you do first is move Week02-ProgressiveInfo/Homework/css back to Week02-ProgressiveInfo/css (locally).
Then add it to your local repo, then push to your remote. 
That should fix the majority of issues.
Next, I'd do a pull from my repo (git pull http://github.com/ZoeLawson/mcc_tools_tech.git Winter2020), which might get things sorted. 
And I misread the other file names, so yeah, that should be it.

**Comment by jasmineplex** [comment]
It took a while,  but I figured it all out finally

**Pull request merged**
