### PR TITLE
Create Week 7 Homework - ReStructuredText- Julio Madrid.rst

### PR DESCRIPTION
**Pull request by juliomadridmcc**

### CODE REVIEW

**Comment by ZoeLawson** [comment]
There are some extra files from other folks in your PR that we need to clean up. I need to figure out what they are, first.

**Comment by ZoeLawson** [comment]
Can you please sync files from Upstream/Winter2022 and push to your repo? (Or sync in GitHub)
I think that will tidy up the PR. (Your PR is including files from other folks, and I don't want to overwrite stuff.)
Thanks!

**Comment by juliomadridmcc** [comment]
Hi Professor,

I think I just did that so please let me know if that worked and you will
be able to accept my pull requests.

- Julio Madrid

**Comment by ZoeLawson** [comment]
I think you still need to push to your GitHub repo. I don't see any changes in the pull request yet.

**Comment by ZoeLawson** [comment]
Perfect! Thanks. Now you're only updating your changes. :-)

**Pull request merged**
