### PR TITLE
Create MadCapFlareHW

### PR DESCRIPTION
**Pull request by TAB-Bear**
Here is what I developed in MCF.
file:///C:/Users/tburns/Documents/My%20Projects/Steak2/Output/tburns/HTML5/Content/Cooking%20Steak.htm

### CODE REVIEW

**Comment by ZoeLawson** [comment]
This PR only contains one file (Create madCapFlareHW) which has no content.
the path you pasted in is to a file on your system, that isn't available in GitHub.
You need to copy the Cooking Steak.htm to the mcc_tools_tech/tree/Winter2020/Week10-PortalsHelp folder (probably in your C:\Users\tburns\Documents\GitHub folder)

**Comment by TAB-Bear** [comment]
Is this correct

**Comment by ZoeLawson** [comment]
There's no new commits, so nothing has changed here in GitHub.
Make sure you move the files you want to upload from your MadCap Flare project to the GitHub Desktop location.
You then need to go into GitHub Desktop and commit the files, then push them to your repo in GitHub.
I can do a screen share tonight if that would help.

**Comment by TAB-Bear** [comment]
I'll try again when I'm through with my class at 12:30. Can't believe how
difficult this is.

**Comment by TAB-Bear** [comment]
Is it good now?

**Comment by ZoeLawson** [comment]
There's still only one commit to this PR, so I haven't seen a change on this end.
Are you getting any messages? Have you moved the files, committed them, and pushed?

**Comment by TAB-Bear** [comment]
Hi Zoe,

Any chance we can hop on a call (617.686.6636) briefly to figure out what I
need to do?

Here's what I'm working with.

[image: image.png]

[image: image.png]

Best,

Todd

**Comment by ZoeLawson** [comment]
This medium stripped the images.
Also, if you can edit your comment, please do, this is a public site.
Can we go into the Webinar in Blackboard collaborate? Then you can share your screen, which might be easier. I'm free until 11. I can also sign in before class around 5.

**Comment by TAB-Bear** [comment]
Hi Zoe,

I'm available now. I'll do this however you think is best. Please let me
know.

Best,

Todd
617.686.6636

**Comment by ZoeLawson** [comment]
I'm waiting in the Webinar

**Pull request merged**
