### PR TITLE
Week_2_Homework_2nd-Try

### PR DESCRIPTION
**Pull request by KristroWriter**

### CODE REVIEW

**Comment by ZoeLawson** [comment]
I can see the homework in the two different commits, so I'm curious what was the 2nd try? :-)

**Comment by KristroWriter** [comment]
Hi Zoe,

Ok, the 2nd try was because I thought I forgot to do the summary for part
of it and redid it, but then realized they were both going to go through.
However, I think I have done something very wrong. I thought I was
following the video, but I don't see any html with my changes.

Kristina

**Comment by ZoeLawson** [comment]
AH ha! 
I shouldn't have tried to do the pull request during a work break. I didn't pay close enough attention.
Your file name is currently KristinaStroberg.properties.properties.
My guess is that you haven't configured File Explorer to show file extentions. See the File Explorer configuration  in the Tips and Tricks PDF in the Handouts folder.
By default, Windows hides known file extensions. This is terrible. :-) However, there's a quick configuration change you can make to show them. Then you can see what files are actually named.

**Comment by KristroWriter** [comment]
so funny, I didn't see this reply and posted this question to discussion
board exactly the same time as you posted it there

**Pull request merged**
