### PR TITLE
Dita SteveB

### PR DESCRIPTION
**Pull request by spbrown001**

### CODE REVIEW

**Comment by ZoeLawson** [comment]
Drat. 
The building of PDFs is causing conflicts.
If you sync with the class repo and push to your repo, that should fix it.

**Comment by spbrown001** [comment]
I think I merged, I compared the merge and it asked me the question and I chose the bottom entry like you showed in class last week.  
My local ditamap file looks ok I think. I see the references in Oxygen:(local)  StephenBrown.ditamap</frontmatter>    <chapter href="Stephen/topic.dita">        <topicref href="Stephen/motorcycle_pre_ride_safety_check.dita"/>    </chapter>    <chapter href="Stephen/horn_and_turn_signals.dita"/>    <chapter href="Stephen/kickstand_check.dita"/>    <chapter href="Stephen/lights.dita"/>    <chapter href="Stephen/fluid_leaks.dita"/>    <chapter href="Stephen/tires_and_tire_inflation.dita"/></bookmap>
But when I go into the github GUI and then do show in Github, the StephenBrown.ditamap is the original copy. 

I think I did the pull request correctly (?):



I see this: 

Seems sync'd:


Not sure,Steve

    On Wednesday, April 20, 2022, 08:27:59 PM EDT, Zoë Lawson ***@***.***> wrote:  
 
 


Drat.
The building of PDFs is causing conflicts.
If you sync with the class repo and push to your repo, that should fix it.

**Comment by ZoeLawson** [comment]
Looks like it worked. I had a green checkmark and could merge.

**Comment by spbrown001** [comment]
Thank you Zoe.

    On Wednesday, April 20, 2022, 09:48:26 PM EDT, Zoë Lawson ***@***.***> wrote:  
 
 


Looks like it worked. I had a green checkmark and could merge.

**Pull request merged**
